#!/bin/bash

set -e

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.java" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs prettier --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
