#!/bin/bash

set -e

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.java" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# format all selected files
mvn com.coveo:fmt-maven-plugin:format

# add back the formatted files to staging
echo "$FILES" | xargs git add

exit 0
